<?php

use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Row;
use Drupal\Core\Link;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row().
 */
function oe_newsroom_connector_item_migrate_newsroom_item_prepare_row (
  Row $row,
  MigrateSourceInterface $source,
  MigrationInterface $migration
) {

  $data = [];

  // Get related nodes.
  $related_content_ids = [];
  $related_content_ids[] = $row->getSourceProperty('parent_content');
  $related_content_ids[] = $row->getSourceProperty('related_content');

  $related_content_ids = array_filter($related_content_ids);

  foreach ($related_content_ids as $id) {
    $nid = _oe_newsroom_connector_item_get_destination_id($migration, $id);
    $node = Node::load($nid);
    if (!empty($node)) {
      $data[] = _oe_newsroom_connector_item_get_link_array("entity:node/{$node->id()}", $node->label());
    }
  }

  // Get see also.
  $see_also_title = $row->getSourceProperty('see_also_text');
  $see_also_url = $row->getSourceProperty('see_also_url');
  if (!empty($see_also_url)) {
    $data[] = _oe_newsroom_connector_item_get_link_array($see_also_url, $see_also_title);
  }

  // Get contact info.
  $contact_title = $row->getSourceProperty('contact_text');
  $contact_info = $row->getSourceProperty('contact_info');
  if (!empty($see_also_url)) {
    $data[] = _oe_newsroom_connector_item_get_link_array($contact_info, $contact_title);
  }

  // Get related documents.
  $related_documents_titles = $row->getSourceProperty('related_documents_title');
  $related_documents_urls = $row->getSourceProperty('related_documents_url');

  if (!empty($related_documents_urls)) {
    if (is_array($related_documents_urls)) {
      foreach ($related_documents_urls as $key => $item) {
        $data[] = _oe_newsroom_connector_item_get_link_array($related_documents_urls[$key], $related_documents_titles[$key]);
      }
    }
    else {
      $data[] = _oe_newsroom_connector_item_get_link_array($related_documents_urls, $related_documents_titles);
    }
  }

  $row->setSourceProperty('links', $data);

  // Full content.
  $full_text = $row->getSourceProperty('body');
  $full_text .= $row->getSourceProperty('quote_box');
  $full_text .= $row->getSourceProperty('linked_object');

  $row->setSourceProperty('full_text', $full_text);

  $subjects = $row->getSourceProperty('subjects');
  $subject_data = [];
  if (!empty($subjects)) {
    if (is_array($subjects)) {
      foreach ($subjects as $subject) {
        $subject_data[] = ['subject' => $subject];
      }
    }
    else {
      $subject_data[] = ['subject' => $subjects];
    }
  }

  $row->setSourceProperty('subjects', $subject_data);
}

/**
 * Gets destination Id.
 *
 * @param \Drupal\migrate\Plugin\MigrationInterface $migration
 *   Migration.
 * @param string $source_id
 *   Source Id.
 *
 * @return mixed
 *   Destination Id.
 */
function _oe_newsroom_connector_item_get_destination_id(MigrationInterface $migration, $source_id) {
  return reset($migration->getIdMap()->lookupDestinationId([$source_id]));
}

/**
 * Gets link array.
 *
 * @param string $url
 *   URL.
 *
 * @param string $title
 *   Title.
 *
 * @return array
 *   Link array.
 */
function _oe_newsroom_connector_item_get_link_array($url, $title) {
  return [
    'url' => $url,
    'title' => $title,
  ];
}

/**
 * Implements hook_entity_extra_field_info().
 */
function oe_newsroom_connector_entity_extra_field_info() {
  $extra = [];

  $extra['node']['oe_news']['display']['newsroom_action_buttons'] = [
    'label' => t('Action buttons'),
    'description' => t('Displays buttons to edit or to reimport newsroom item.'),
    'weight' => 100,
    'visible' => TRUE,
  ];

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function oe_newsroom_connector_node_view(
  array &$build,
  EntityInterface $entity,
  EntityViewDisplayInterface $display,
  $view_mode
) {

  if ($entity->bundle() == 'oe_news') {
    // Newsroom action buttons.
    if ($display->getComponent('newsroom_action_buttons')) {
      $newsroom_id = $entity->field_newsroom_id->value;
      if (!empty($newsroom_id)) {
        $universe_manager = \Drupal::service('oe_newsroom_connector.universe_manager');
        $items = [
          Link::fromTextAndUrl('Edit', $universe_manager->getItemEditUrl($newsroom_id))->toRenderable(),
          Link::fromTextAndUrl('Import', URL::fromRoute('oe_newsroom_connector.import', [
            'type' => 'item',
            'newsroom_id' => $newsroom_id,
          ]))->toRenderable(),
        ];
        $build['newsroom_action_buttons'] = [
          '#theme' => 'item_list',
          '#items' => $items,
        ];
      }
    }
  }

}