<?php

use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Row;
use Drupal\Core\Link;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Url;

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row().
 */
function oe_newsroom_connector_migrate_newsroom_item_prepare_row (
  Row $row,
  MigrateSourceInterface $source,
  MigrationInterface $migration
) {
  $related_documents_titles = $row->getSourceProperty('related_documents_title');
  $related_documents_urls = $row->getSourceProperty('related_documents_url');

  $data = [];
  if (!empty($related_documents_urls)) {
    if (is_array($related_documents_urls)) {
      foreach ($related_documents_urls as $key => $item) {
        $data[$key]['url'] = $related_documents_urls[$key];
        $data[$key]['title'] = $related_documents_titles[$key];
      }
    }
    else {
      $data[0]['url'] = $related_documents_urls;
      $data[0]['title'] = $related_documents_titles;
    }
  }
  $row->setSourceProperty('documents', $data);
}

/**
 * Implements hook_entity_extra_field_info().
 */
function oe_newsroom_connector_entity_extra_field_info() {
  $extra = [];

  $extra['node']['oe_news']['display']['newsroom_action_buttons'] = [
    'label' => t('Action buttons'),
    'description' => t('Displays buttons to edit or to reimport newsroom item.'),
    'weight' => 100,
    'visible' => TRUE,
  ];

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function oe_newsroom_connector_node_view(
  array &$build,
  EntityInterface $entity,
  EntityViewDisplayInterface $display,
  $view_mode
) {

  if ($entity->bundle() == 'oe_news') {
    // Newsroom action buttons.
    if ($display->getComponent('newsroom_action_buttons')) {
      $newsroom_id = $entity->field_newsroom_id->value;
      if (!empty($newsroom_id)) {
        $universe_manager = \Drupal::service('oe_newsroom_connector.universe_manager');
        $items = [
          Link::fromTextAndUrl('Edit', $universe_manager->getItemEditUrl($newsroom_id))->toRenderable(),
          Link::fromTextAndUrl('Import', URL::fromRoute('oe_newsroom_connector.import', [
            'type' => 'item',
            'newsroom_id' => $newsroom_id,
          ]))->toRenderable(),
        ];
        $build['newsroom_action_buttons'] = [
          '#theme' => 'item_list',
          '#items' => $items,
        ];
      }
    }
  }

}
